// AlertItem is a backward-compat alias for the generated Alert schema.
// The hooks (useListAlerts, useMarkAlertRead) are now generated by orval.
export type { Alert as AlertItem } from "./generated/api.schemas";
